apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-chat-config
data:
  MONGO_HOST: ai-chat-db-svc:27017
  MONGO_DB: ai-chat
  OLLAMA_URL: ai-chat-model-svc:11434
  OLLAMA_MODEL: smollm2:135m

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-chat-secrets
type: Opaque
stringData:
  MONGO_USER: admin
  MONGO_PASSWORD: password
